dependencies {
    minecraft libs.minecraft
    mappings loom.layered() {
        officialMojangMappings()
        parchment variantOf(libs.parchment) {
            artifactType('zip')
        }
    }
    modImplementation libs.fabricLoader
    modImplementation libs.fabricApi
    modImplementation "com.terraformersmc:modmenu:${modmenu_version}"

    modImplementation(libs.balmFabric) {
        changing = libs.versions.balm.get().contains("SNAPSHOT")
        exclude group: "net.blay09.mods", module: "shared-bridge"
    }
    modImplementation(libs.kumaFabric)

    modImplementation "dev.isxander:yet-another-config-lib:${project.yacl_version}+${project.yalc_mc}-fabric"
}
