subprojects {
    apply plugin: 'java'
    java.withSourcesJar()
    java.withJavadocJar()

    repositories {
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }

    sourceSets {
        main {
            java {
                srcDir project(':modules:universal').file('common/src/main/java')
            }
            resources {
                srcDir project(':modules:universal').file('common/src/main/resources')
            }

            if (project.name.startsWith("fabric")) {
                java.srcDir project(':modules:universal').file('fabric/src/main/java')
            }
            if (project.name.startsWith("forge")) {
                java.srcDir project(':modules:universal').file('forge/src/main/java')
            }
        }
    }

    if (project.name.startsWith("forge")) {
        tasks.withType(Javadoc).configureEach {
            enabled = false
        }
    }
}