# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
mod_id=qualityofqueso
mod_version=1.7.1
mod_name=Quality of Queso
description=Chest searching, container filtering, precise inventory management, and more!
mod_author=Dillon8775, MannyQUESO
credits=Dillon8775, MannyQUESO
license=All rights reserved.
logo=assets/qualityofqueso/icon
mc_version=mc1.20.1
supported_mc_versions=[1.20.1]
minecraft_version_range=[1.20.1, 1.20.2)
group=net.dillon.qualityofqueso

# Links
homepage=https://modrinth.com/mod/quality-of-queso
sources=https://github.com/Dillon8775/Quality-of-Queso
issues=https://github.com/Dillon8775/Quality-of-Queso/issues
discord=https://discord.gg/vfqEAn4YFy

# Common
java_version=17
minecraft_version=1.20.1

# IDs
curseforge_project_id=1275791
modrinth_project_id=Sj7HGYie

# Balm version
balm_version=7.3.38

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=
fabric_loader_version=
modmenu_version=7.2.2

# Changelog and Misc
changelog_file=current_changelog.md

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false