# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
mod_id=qualityofqueso
mod_version=1.7.11
mod_name=Quality of Queso
description=A Fabric/(Neo)Forge mod that adds various different QoL features, including container searching, precise inventory management, cool visual effects, and so much more!
mod_author=Dillon8775, MannyQUESO
credits=Dillon8775, MannyQUESO
license=All rights reserved unless explicitly stated.
logo=assets/qualityofqueso/icon
mc_version=mc1.21.11
supported_mc_versions=1.21.11
minecraft_version_range=[1.21.11, 1.21.12)
group=net.dillon.qualityofqueso

# Links
homepage=https://modrinth.com/mod/quality-of-queso
sources=https://github.com/Dillon8775/Quality-of-Queso
issues=https://github.com/Dillon8775/Quality-of-Queso/issues
discord=https://discord.gg/vfqEAn4YFy

# Common
java_version=21
minecraft_version=1.21.11

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050

# Balm version
balm_version=21.11.9

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.141.4+1.21.11
fabric_loader_version=0.18.6
modmenu_version=17.0.0

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=21.11.42
neoforge_loader_version_range=[4,)

# YetAnotherConfigLib
yacl_version=3.8.2
yalc_mc=1.21.11

# Other (not required in multiloader-common.gradle)
curseforge_project_id=1275791
modrinth_project_id=Sj7HGYie
changelog_file=current_changelog.md

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false