repositories {
    maven {
        name = 'Forge'
        url = 'https://maven.minecraftforge.net'
        content {
            includeGroupAndSubgroups 'net.minecraftforge'
        }
    }

    maven {
        url "https://maven.terraformersmc.com/releases/"
    }

    maven {
        url = 'https://maven.twelveiterations.com/repository/maven-public/'
        content {
            includeGroup 'net.blay09.mods'
        }
    }

    maven {
        name = 'Twelve Iterations'
        url = 'https://maven.twelveiterations.com/repository/maven-public/'
        content {
            includeGroup 'net.blay09.mods'
        }
    }

    maven {
        name = 'isXander'
        url = 'https://maven.isxander.dev/releases'
    }

    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
    }

    maven {
        name = 'CurseMaven'
        url = 'https://www.cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }

    maven {
        name = 'BlameJared'
        url = 'https://maven.blamejared.com'
        content {
            includeGroup "mezz.jei"
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = 'Minecraft'
                url = 'https://libraries.minecraft.net/'
                metadataSources {
                    mavenPom()
                    artifact()
                }
            }
        }
        filter { includeGroupAndSubgroups("com.mojang") }
    }
}
