repositories {
    maven {
        url "https://maven.terraformersmc.com/releases/"
    }
    maven {
        name = 'Twelve Iterations'
        url = 'https://maven.twelveiterations.com/repository/maven-public/'
        content {
            includeGroup 'net.blay09.mods'
        }
    }
    maven {
        name = 'isXander'
        url = 'https://maven.isxander.dev/releases'
    }
    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
    }

    maven {
        name = 'CurseMaven'
        url = 'https://www.cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }

    maven {
        name = 'BlameJared'
        url = 'https://maven.blamejared.com'
        content {
            includeGroup "mezz.jei"
        }
    }

    maven {
        name = "QuiltMC"
        url = "https://maven.quiltmc.org/repository/release/"
    }

    exclusiveContent {
        forRepository {
            maven {
                name = 'Minecraft'
                url = 'https://libraries.minecraft.net/'
            }
        }
        filter { includeGroupAndSubgroups("com.mojang") }
    }
}
